### ISSUE TITLE
You included a private key in your public repository!!!

### ISSUE THREAD

**Issue by ghost** [jayantsharma/dotfiles#1]
You have included your private SSH key, that I presume you use to authenticate over with GitHub, but still leaves your GitHub vulnerable, available to public (something that you should never do). You should probably just DELETE this REPOSITORY entirely and create a new one, not including the private key (i.e. **.ssh/id_rsa**)

Cheers!

**Comment by jayantsharma** [comment]
Thanks for pointing this out! Why can't I just delete the private key from the repo ? 

Why delete the whole repo ?

**Comment by ghost** [comment]
Mostly because all of the changes that you ever made to the repository can be seen by anyone. I'm no git wiz by no means, but re—creating the repo seems like a safer thing to do in my opinion.

**Comment by jayantsharma** [comment]
I don't think it should matter because the repo is public anyways. 

Just curious, how did you come across the repo ?

**Comment by jayantsharma** [comment]
kyghjkg

**Comment by ghost** [comment]
I was looking for more information on Asus X205TA as I'm planning to get Arch running on this little beast.

**Comment by ghost** [comment]
Oh and yes, I guess you could just re—generate the key. Silly of me :)

**Comment by jayantsharma** [comment]
Oh, great. I've written an article on my experience here :
http://panickypika.blogspot.in/.

You might find it of interest :)

Although the arch wiki pretty much covers it up.

**Comment by jayantsharma** [comment]
Yeah, that's exactly what I did.

**Comment by ghost** [comment]
Oh cool, so how are you happy with the notebook so far and what's the battery life like on Linux? Are you able to get any (serious?) work done on it, programming wise.

**Comment by jayantsharma** [comment]
My motherboard is a serious worry for me. I've got it replaced twice in a
year (on warranty). And no sound!

It's great for running arch otherwise. Battery easily runs for 8+ hours. No
problems programming wise, although I do not run processing-heavy
programs/scripts. Tends to slow down after 20-25+ tabs on firefox.

All in all, it's a neat little machine.
